Repository guardian/support-service-lambdas, pull requests merged in 2025-09, with the labels that each got.

#3047 Stop holiday-stop-api sending duplicated authorisation headers in Salesforce requests
  lib/salesforce/client/src/main/scala/com/gu/salesforce/SalesforceClient.scala
Labels: Change failure fix

#3048 Add term type and length to product catalog
  modules/product-catalog/src/generateProductCatalog.ts
  modules/product-catalog/src/generateSchema.ts
  modules/product-catalog/src/productCatalog.ts
  modules/product-catalog/src/productCatalogSchema.ts
  modules/product-catalog/src/stripeProducts.ts
  modules/product-catalog/src/zuoraToProductNameMappings.ts
  modules/product-catalog/test/__snapshots__/generateProductCatalog.test.ts.snap
  modules/zuora-catalog/src/zuoraCatalogSchema.ts
  modules/zuora-catalog/test/fixtures/catalog-code.json
  modules/zuora-catalog/test/fixtures/catalog-prod.json
Labels: Feature

#3055 Remove the contribution charge from S+ student plan
  modules/product-catalog/src/productCatalogSchema.ts
  modules/product-catalog/test/__snapshots__/generateProductCatalog.test.ts.snap
  modules/zuora-catalog/test/fixtures/catalog-code.json
  modules/zuora-catalog/test/fixtures/catalog-prod.json
Labels: Maintenance

#3041 Add streaming functionality to S3 tests and enhanced SAR download experience
  cdk/lib/__snapshots__/mparticle-api.test.ts.snap
  cdk/lib/cdk/sr-lambda.ts
  cdk/lib/mparticle-api.ts
  handlers/mparticle-api/runManual/invokeHandlerSARStatus.ts
  handlers/mparticle-api/src/index.ts
  handlers/mparticle-api/src/routers/baton/access/handleStatus.ts
  handlers/mparticle-api/src/routers/http.ts
  handlers/mparticle-api/src/routers/http/dataSubjectRequestCallback/data-subject-request-callback.ts
  handlers/mparticle-api/src/services/batonS3Writer.ts
  handlers/mparticle-api/test/access/handleStatusIntegration.test.ts
  handlers/mparticle-api/test/baton.spec.ts
  handlers/mparticle-api/test/services/batonS3Writer.test.ts
  modules/aws/src/s3FileExists.ts
  modules/aws/test/s3.test.ts
  modules/aws/test/s3FileExists.test.ts
Labels: Feature, Maintenance

#3052 feat(stripe-disputes): Implement event-driven architecture using AWS SQS
  cdk/lib/__snapshots__/stripe-disputes.test.ts.snap
  cdk/lib/stripe-disputes.ts
  handlers/stripe-disputes/package.json
  handlers/stripe-disputes/riff-raff.yaml
  handlers/stripe-disputes/src/consumer.ts
  handlers/stripe-disputes/src/handlers/disputeClosedHandler.ts
  handlers/stripe-disputes/src/handlers/disputeCreatedHandler.ts
  handlers/stripe-disputes/src/handlers/index.ts
  handlers/stripe-disputes/src/index.ts
  handlers/stripe-disputes/src/producer.ts
  handlers/stripe-disputes/src/services/index.ts
  handlers/stripe-disputes/src/services/sqsEventHandler.ts
  handlers/stripe-disputes/src/services/upsertSalesforceObject.ts
  handlers/stripe-disputes/src/services/webhookHandler.ts
  handlers/stripe-disputes/src/sqs-consumers/index.ts
  handlers/stripe-disputes/src/sqs-consumers/listenDisputeClosed.ts
  handlers/stripe-disputes/src/sqs-consumers/listenDisputeCreated.ts
  handlers/stripe-disputes/test/consumer.test.ts
  handlers/stripe-disputes/test/handlers/disputeClosedHandler.test.ts
  handlers/stripe-disputes/test/handlers/disputeCreatedHandler.test.ts
  handlers/stripe-disputes/test/index.test.ts
  handlers/stripe-disputes/test/producer.test.ts
  handlers/stripe-disputes/test/services/sqsEventHandler.test.ts
  handlers/stripe-disputes/test/sqs-consumers/listenDisputeClosed.test.ts
  handlers/stripe-disputes/test/sqs-consumers/listenDisputeCreated.test.ts
  pnpm-lock.yaml
Labels: Feature

#3072 Rename `SupportInternationalisationId` to `SupportRegionId`
  modules/internationalisation/src/countryGroup.ts
Labels: Feature
